### ISSUE TITLE
Request error: 0 on submit

### ISSUE THREAD

**Issue by Vadorequest** [joecorcoran/judge#16]
I don't understand why I get the message `Request error: 0` when I submit a valid form. All fields are valid but when I send the form then the field becomes invalid with this message while the form is sent. The form is sent correctly, it's just the client side validation that does that for one second.

If I take a look to the sent request, 

```
Request URL:http://www.holdsport.dev:3000/validate?klass=club&attribute=name&value=teste&kind=uniqueness
Request Headers CAUTION: Provisional headers are shown.
Accept:application/json
Referer:http://www.holdsport.dev:3000/signup/new_club
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36
X-Requested-With:XMLHttpRequest
Query String Parametersview sourceview URL encoded
klass:club
attribute:name
value:teste
kind:uniqueness
```

That's all, no preview, no response from server. But the uniqueness works well otherwise.

Any idea?

**Comment by nickrivadeneira** [comment]
I'm getting the same issue when using Firefox. Does not occur in Chrome. The request does not receive a response.

I noticed in one of your snippets in another issue, you're basically just filtering that error code out. Have you found another solution since then?
