### ISSUE TITLE
judge.validate don't call the trigger valid/invalid function in a special case

### ISSUE THREAD

**Issue by Vadorequest** [joecorcoran/judge#23]
Hi, I'm trying to understand why in this special case, neither my method `_valid` and `_invalid` are called once the validation is executed.

When I have an input that have a regex such as: 
`validates :mobile, format: { with: /^(\W*\d){6,10}\W*$/ }, allow_blank: true`

If I type a character in the input and if I delete it (empty input) my view is not updated, still red. https://docs.google.com/file/d/0ByzbHcAxmCyvWWI1c1kzbDF4YlE
Of course there is more than `judge.js` to do so, here is the script managing the view update: https://github.com/Vadorequest/judge-bootstrap3-helper/blob/master/js/judge.js

I tried some things and here is what I'm sure:
+ judge.js:217 : the status is correct and displayed correctly.
+ Neither my methods `_valid`/`_invalid` are called (tried to log at the first line for both)

So, I don't get it because my log line 217 is correctly executed and displays the good value, but the trigger doesn't work.

Any idea?

**Comment by jamesmk** [comment]
Looks like this was fixed in https://github.com/joecorcoran/judge/pull/49. Let us know if you're still experiencing the issue after updating.
