### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of null 

### ISSUE THREAD

**Issue by gauravtiwari** [joecorcoran/judge#35]
Hello @joecorcoran I am getting above JS error when using this Gem with Rails 4.1.5 + ruby 2.1 (simple_form). Any fix for this?

Thanks,
Gaurav

**Comment by dannysperry** [comment]
going off of what @wnm said, its quite possible that you are passing a jquery object to judge.validate, if you want to get the actual html element inside the jquery object you would have to change:

```
judge.validate ( $("#some-id"), ...
```

to:

```
judge.validate ( $("#some-id")[0], ...
```

**Comment by jamesmk** [comment]
@gauravtiwari Let us know if you're still experiencing the issue after trying @wnm and @dannysperry's solution. Otherwise I'll close this one out. 

Thanks

**Comment by gauravtiwari** [comment]
Yes, thanks @jamesmk @wnm and @dannysperry

**Comment by jamesmk** [comment]
:+1:

**Comment by tuckerwales** [comment]
Thanks for finding a solution to this, guys.
