### ISSUE TITLE
Gem 'validates_timeliness' and ignored

### ISSUE THREAD

**Issue by MarinoGit** [joecorcoran/judge#40]
I´m using the gem 'validates_timeliness' in a project. In this project I have a validation like this:

validates 		:fechafin, presence: true
validates_date 	:fechafin, :after => :fechainicio,
				:after_message => "debe ser mayor o igual que la fecha de inicio"

where 'fechainicio' is another field of the model.

And judge gem generates validators like this:

<input class="form-control" data-validate="[{"kind":"presence","options":{},"messages":{"blank":"Por favor, rellena la fecha de fin"}},{"kind":"timeliness","options":{"after":"fechainicio","after_message":"debe ser mayor o igual que la fecha de inicio"},"messages":{}}]" type="text">

How i could mark the "validates_date" validation? I have test with this line but doesn´t works:

validates_date  :fechafin, :judge => ignore, :after => :fechainicio,
		         :after_message => "debe ser mayor o igual que la fecha de inicio"

**Comment by jamesmk** [comment]
@MarinoGit Judge only supports validations native to Rails out of the box. The validates_timeliness gem creates a custom validator (https://github.com/adzap/validates_timeliness/blob/master/lib/validates_timeliness/validator.rb), so unfortunately the cooresponding javascript will have to be written. Documentation on working with custom validators is in the wiki:

https://github.com/joecorcoran/judge#writing-your-own-eachvalidator
