### ISSUE TITLE
mailboxer raise an error after added judge initializer for validates uniqueness

### ISSUE THREAD

**Issue by apinrdw** [joecorcoran/judge#43]
This issue came when i added judge initializer to expose User email.

The error raise 'method_missing': undefined local variable or method 'acts_as_messageable'.
![judge](https://cloud.githubusercontent.com/assets/4516973/5358609/c88a1dfa-7fe8-11e4-8191-9dc254d01e29.png)

When i comment the initializer everything is work fine.
tested using Rails 4.1.8 and 4.1.6 with Ruby 2.1.2.

**Comment by joecorcoran** [comment]
Hmm, sounds like a load order issue. How are you expecting `acts_as_messageable` to be made available to your project? Bundler?

**Comment by apinrdw** [comment]
I think its Bundler. acts_as_messageable is a module from mailboxer gem. Is there problem with load order in my gemfile?

**Comment by apinrdw** [comment]
I got another bug to sorcery gem , since i already remove the mailboxer gem.

*If i initialize Judge configure on config/initializers/judge.rb*
Any methods and attributes defined on sorcery is inaccessible. Maybe happen to another, i not test everything.

solution:
*added to config/application.rb*
```ruby
config.after_initialize do
  Judge.configure do
    expose User, :email, :username
    # etc
  end
end
```

I think this will solve this issue... :)
