### ISSUE TITLE
Maintainers needed!

### ISSUE THREAD

**Issue by joecorcoran** [joecorcoran/judge#47]
Due to various circumstances, I haven't had enough time or energy in the past year to give this gem the attention it deserves. I no longer use it in my day job, so there is no potential for paid maintenance going forward.

Judge is – as far as I can tell – the most widely-used client-side validation gem around these days, at least in terms of projects that are still actively maintained. If you'd like to help me out in any way, I would really appreciate it. I know there are enough of you out there to share the load. :)

I'd love to give commit access to a handful of people. We could even move the project to its own org, if there's any advantage to doing so. New maintainers would need to:

* Triage issues/pull requests
* Keep improving the code, writing tests with RSpec and Jasmine
* Make the documentation better (the README is all we have these days, but I know we can do better than that!)

Please reply here if you're interested! I'm especially keen to hear from people who use Judge already, but that doesn't have to be the case. I think Judge is quite a simple project despite the fact that it bridges the client-server gap. If you're relatively new to Rails, helping out with maintenance might be a good way to improve your Ruby or JavaScript skills. Beginners, consider yourselves very welcome. :)

**Comment by activestylus** [comment]
Are you using any sort of alternative at your job? Or is client side validation no longer a part of your duties?

**Comment by dannysperry** [comment]
I sent you an email

**Comment by joecorcoran** [comment]
@activestylus I changed jobs (and countries) and haven't needed to introduce Judge on any projects since then.

@dannysperry Thanks! Will take a look.

**Comment by saurabhbhatia** [comment]
@joecorcoran I am interested. Not a user yet, but its an interesting project for sure.

**Comment by joecorcoran** [comment]
Okay, so @dannysperry has been doing some great work recently helping with issues etc. @jamesmk got in touch to say that he is interested in helping, as did @saurabhbhatia.

I could make all three of you collaborators on here and also the ability to publish new gem versions to Rubygems. You can figure out a system for accepting pull requests, whatever works best for you all. Does that sound sensible?

**Comment by jamesmk** [comment]
@joecorcoran Sounds good, look forward to working with everyone!

**Comment by saurabhbhatia** [comment]
@joecorcoran @jamesmk @dannysperry Sounds Great! excited to work with everyone.

**Comment by AndrewHendrie** [comment]
I'm interested in helping as well. Using the gem in a current project (and may be using it in future projects). Let me know how I can help :)

**Comment by joecorcoran** [comment]
Thanks @AndrewHendrie! Now that we have a handful of people already, I'm gonna leave it up to the team to add new maintainers to the project. They're a friendly bunch :) Maybe you could have a look through the currently open issues and see what needs to be done?

**Comment by jamesmk** [comment]
Anyone can get involved supporting issues and opening their own PRs. I'm not opposed to more collaborators, but we have a few now and I'd prefer to add people that are engaging in the project. 

Thanks everyone!
