### ISSUE TITLE
Wait until the form field is un-focused for validation

### ISSUE THREAD

**Issue by ErikVDW** [joecorcoran/judge#50]
Hi,

I'm just wondering if Judge is supposed to use this ^ automatically or if the expected behavior is for Judge to validate all of the fields before they are ever entered by the user.  For me, Judge is showing a form of red before the user enters anything.

Thanks,
Erik

**Comment by dannysperry** [comment]
Hi @ErikVDW,

how judge validates your inputs is specified in your application JS. Judge validates with judge.validate() inside your JS. 

it is possible you are calling something like 
```
$(document).ready(function () {
  judge.validate(your_element_here);
});
```

**Comment by dannysperry** [comment]
This seems like an implementation issue. Make sure you are calling judge.validate on the an event if you don't want validation to occur on page load.
