### ISSUE TITLE
`func.apply` in `_.once` is breaking my asynchronous validations

### ISSUE THREAD

**Issue by zacharyabresch** [joecorcoran/judge#59]
Hi. I've been working on a Coffeescript class to handle Judge validations. It is based off a Javscript I found [here][1]. It's throwing errors related to Underscore.js.

When I instantiate my class `judgment = new JudgeJudy({form: $("#new_suggestion")})` I'm seeing this error in the console:

```
Uncaught TypeError: func.apply is not a function
```

and it references line 683 in the Underscore.js library.

***

Here's that Coffeescript:

```coffeescript
# This class was inspired by code found
# here: http://blog.bananacoding.com/blog/client-side-form-validation-using-judge-gem

@JudgeJudy = class JudgeJudy
  constructor: (@options)->
    @form = @options.form
    @validate_form()

  valid: (element, deferred)->
    $(element).removeClass('error').addClass('valid')
    deferred.resolve()

  invalid: (element, deferred)->
    $(element).removeClass('valid').addClass('error')
    deferred.reject()

  validate_form: ->
    that = @
    @form.on 'submit', (event) ->
      event.preventDefault()
      $('.error_container').empty()

      defers = []

      that.form.find('.form-control').each (index, element)->
        defers.push(that.validate_input_async(element))

      $.when.apply($, defers).done ->
        that.form.unbind 'submit'
        that.form.submit()

  validate_input_async: (element)->
    deferred = new $.Deferred()

    q = judge.validate element,
      valid:
        @valid element, deferred
      invalid:
        @invalid element, deferred

    deferred.resolve() if q.validations.length
    deferred
```

I was poking around the Judge repository and noticed that the Underscore version in use is 1.4.4 but Underscore.js is currently at 1.8.3. I'm not sure if it's my code, Underscore, or something else but I'm wondering how you would recommend I update this Underscore library to the latest version to see if that resolve my issue. 

I struggled for a whole day thinking it was *my* call to `apply` on `$.when` that was throwing the error but then I got smart and actually looked at the error message closely. :smile_cat: 

If you've got any feedback or ideas I'm *all* ears!!

[1]:http://blog.bananacoding.com/blog/client-side-form-validation-using-judge-gem

**Comment by zacharyabresch** [comment]
So, I dropped in the `underscore-rails` gem and ... this error cropped up again but on a *different* method (`_.before`), same code (`memo = func.apply(this, arguments);`). Looks like I'll need to take this up with the Underscore repository. If you've got any input I'd love to hear it but I'd also understand if you wanted to close this issue since it doesn't look to be an actual issue on Judge.

**Comment by jamesmk** [comment]
Yeah, looks like it may be an issue with the coffeescript or dependency order. Unfortunately I'm not great with coffeescript so I'm not much help here.

Since this isn't an issue with the gem I'm going to close this one out.

**Comment by zacharyabresch** [comment]
After posting over in the Underscore repo it was pointed out to me that I wasn't properly creating the callbacks as methods. I've been staring at this code by myself for so long I'd totally missed it.  In case anyone needs to know, this is the fix that did it. 

```coffeescript
q = judge.validate element,
      valid: (element)=>
        @valid element, deferred
      invalid: (element)=>
        @invalid element, deferred
```
