### ISSUE TITLE
Ruby -> JavaScript regexp support

### ISSUE THREAD

**Issue by joecorcoran** [joecorcoran/judge#6]
There are big differences between the regular expression capabilities of Ruby and JavaScript. It's not within the scope of this project to bridge the gap, but it does cause problems for certain typical uses of the format validator. See issue #5 for an example.

At the moment, I'm thinking that the best way to solve this is to write a plugin for [XRegExp](https://github.com/slevithan/XRegExp) which will add some of the more commonly used [Oniguruma](http://www.geocities.jp/kosako3/oniguruma/) features (character types and anchors, POSIX bracket syntax for character classes). We can then use XRegExp in place of the native RegExp in Judge's client-side format validator method.

**Comment by slevithan** [comment]
For anyone reading this all these years later, check out https://github.com/slevithan/oniguruma-to-es to easily translate Oniguruma / Ruby regexes to JS.
