### ISSUE TITLE
update Rails/Ruby support

### ISSUE THREAD

**Issue by jamesmk** [joecorcoran/judge#84]
Hey @joecorcoran,

I think we should take a look at updating our Ruby and Rails support moving forward. I'd be down to update Appraisals/Travis once we agree on versions. My suggestion would be:

Ruby 2.2+
Rails 5.0+

What do you think?
thanks

**Comment by joecorcoran** [comment]
I don't really have much of a handle on Rails version uptake these days, so if you think that sounds reasonable, go right ahead. 👍
